language: node_js
node_js: node
cache:
  directories:
  - node_modules
  - bower_components

before_script:
- yarn install
- bower install

script:
- gulp build

after_success:
 - if [ "$TRAVIS_BRANCH" = "master" ]; then firebase deploy --project $FIREBASE_PROJECT_ID --token "$FIREBASE_TOKEN"; fi